### ISSUE TITLE
pyrealsense2 installation

### ISSUE THREAD

**Issue by maheshs11** [aleannox/leo#1]
how did u install this library?

**Comment by aleannox** [comment]
I followed these instructions https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_raspbian.md

**Comment by maheshs11** [comment]
we need real sense camera or we can get frames from any webcam like in opencv ?

**Comment by aleannox** [comment]
You can use any webcam of course, if you adapt the code accordingly.
